# Generated by Django 3.2.8 on 2021-10-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('five_crowns_scorecard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-game_date']},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('game', 'player', 'points')},
        ),
    ]
