# Generated by Django 3.2.8 on 2021-10-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_crowns_scorecard', '0002_rename_scores_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='player',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='lowest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateField(),
        ),
    ]
